# Generated by Django 5.1.3 on 2024-11-28 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_no', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('delivery_method', models.CharField(choices=[('ngo', 'NGO Pickup'), ('self', 'Self Delivery')], max_length=4)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('dropoff_location', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('packaged', 'Packaged Foods'), ('canned', 'Canned Foods'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('other', 'Other')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('condition', models.CharField(choices=[('new', 'New/Unused'), ('near', 'Near Expiry')], max_length=4)),
                ('expiration_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='food_items/')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='foodshare_app.fooddonation')),
            ],
        ),
    ]
