# Generated by Django 5.1.3 on 2024-11-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='food_items/'),
        ),
    ]
