# Generated by Django 5.1.3 on 2024-11-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare_app', '0002_alter_fooditem_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='condition',
            field=models.CharField(choices=[('new', 'New/Unused'), ('near', 'Near Expiry')], max_length=50),
        ),
    ]
