# Generated by Django 5.1.3 on 2024-12-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodshare_app', '0003_alter_fooditem_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_hold', 'On Hold'), ('redistributed', 'Redistributed'), ('discarded', 'Discarded')], default='pending', max_length=15),
        ),
    ]
